### ISSUE TITLE
Switch View Error because enable failed

### ISSUE THREAD

**Issue by markus-posch** [obrigg/Vanilla-ISE#10]
Hello, 

i set up Vanilla-ISE as Docker Container with Docker Compose.
The Switch View is not working with the Error "An error has occurred. (Details: ['ERROR: Problem connecting to 172.20.201.80...'])"
The Switch logging shows enable failed.

In the docker-compose.yaml i have the line where the real password is used instead of the word password
- SWITCH_ENABLE=password

**Comment by obrigg** [comment]
Can you try to use `docker-compose logs --tail` and look at the actual connection prompt to better understand what's happening?

**Comment by markus-posch** [comment]
Hello,

below the log data
I'm sure I entered the password correctly as an environment variable

```
023-05-04 08:29:52,475: %UNICON-INFO: +++ connection to spawn: ssh -l billibob 172.37.127.15 -p 22 -o KexAlgorithms=+diffie-hellman-group14-sha1, id: 140055276866048 +++
2023-05-04 08:29:52,476: %UNICON-INFO: connection to device
yes
Warning: Permanently added '172.37.127.15' (RSA) to the list of known hosts.
Password: 
swazkxz0701>
2023-05-04 08:29:53,257: %UNICON-INFO: Learned hostname(s): 'swazkxz0701'.
2023-05-04 08:29:53,257: %UNICON-INFO: +++ initializing handle +++
enable
Password: 
% Access denied
swazkxz0701>ERROR: Problem connecting to 172.37.127.15...
```
