### ISSUE TITLE
Allow flexibility with MAC address format

### ISSUE THREAD

**Issue by eiddor** [obrigg/Vanilla-ISE#3]
Inputting a MAC Address in Endpoint Query requires the `aa:bb:cc:dd:ee:ff` format, however the output format in Device Query and even in error messages is `aaaa.bbbb.cccc`

We should be able to copy/paste between output and input.

![image](https://user-images.githubusercontent.com/7586731/155379857-5855db03-e200-4412-811b-c73dc7dc7344.png)

![image](https://user-images.githubusercontent.com/7586731/155380002-213063ed-fcab-4bb6-8a80-49b6900dca5d.png)

![image](https://user-images.githubusercontent.com/7586731/155380075-8fd2439e-3792-490d-a0da-354e988761b3.png)

**Comment by RamonaR** [comment]
The latest master commits now allow the use of multiple MAC formats (e.g. xxxxxxxxxxxx, xx-xx-xx-xx-xx-xx, xx.xx.xx.xx.xx.xx or xxxx.xxxx.xxxx, xx:xx:xx:xx:xx:xx) in the endpoint query search field and the MAC address field of the add voucher modal.

<img width="563" alt="image" src="https://user-images.githubusercontent.com/6546458/167368926-a1cb75bb-9ca6-4e8b-8210-f4e4514947a6.png">

<img width="734" alt="image" src="https://user-images.githubusercontent.com/6546458/167368586-0a68123a-9587-4d1c-bfcf-5c2d88e5871e.png">
