### ISSUE TITLE
Link Endpoint MAC in Device Query Page to Endpoint Query

### ISSUE THREAD

**Issue by eiddor** [obrigg/Vanilla-ISE#4]
We should be able to click an Endpoint MAC from the Device Query page and be directed to an Endpoint Query.

Due issue #3 we can't even copy and paste between the queries.

**Comment by RamonaR** [comment]
We added MAC and IP address links on the query device page and other pages that redirect to the endpoint query and switch view page. Duplicate "Query Device" text links were removed.
