### ISSUE TITLE
Problem with environment variables

### ISSUE THREAD

**Issue by eneskayahan** [obrigg/Vanilla-ISE#8]
exactly how i will set that up?
I edited that
export ISE_IP= <ISE hostname/IP>
export ISE_USER= <ISE username>
export ISE_PASSWORD= <ISE password>
export SYSLOG_SERVER= <Syslog server IP, for auditing>
export SWITCH_USER= <username for network devices>
export SWITCH_PASS= <password for network devices>
export SWITCH_ENABLE= <enable password for network devices>

 but when  i activate the env it gives me this error:
bash: env/bin/activate: line 67: syntax error near unexpected token `newline'
bash: env/bin/activate: line 67: `export ISE_IP= <my_ise_ip>'

how can i solve this?

**Comment by eneskayahan** [comment]
export ISE_IP="my ip"

there shoıuld be no space after "=" and instead of "<>" you need to use ""

**Comment by obrigg** [comment]
I'm glad to see things are working now 👍
